### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by PowerX-NF** [Zode/blenderutils#1]
ModuleNotFoundError = No Module named 'blenderutil=1'

I use blender 2.92.0

**Comment by Zode** [comment]
Did you try to install from a release zip?
Try to install it from a master-zip instead (that is: download the master branch of the repo)
This seems to be a bug in the blender itself where its for some reason hardcoded to seek out the master branch zip name

**Comment by Zode** [comment]
I assume the above comment had fixed this issue as i haven't heard anything
